.PHONY: help
help:
	@echo "\033[34m------------\033[0m"
	@echo "  Demo gif  "
	@echo "\033[34m------------\033[0m"
	@echo "- play"
	@echo "- render"

.PHONY: play
play: ## plays the input file to terminal
	terminalizer play -r home-demo.yml

.PHONY: render
render: ## renders to a .gif
	terminalizer render home-demo.yml