name: Release

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64, arm64]
    
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.36
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: 1.18
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}